version: "3.7"
services:
  appd-db-agent:
    image: appd-db-agent
    network_mode: host
    build: appd-db-agent
    command: /opt/appd-dbagent/start-dbagent -Ddbagent.name="${DB_AGENT_NAME:-north-west-blue}"
    environment:
     - DB_AGENT_NAME